export const  AppConstants = {
    APP_URL : "http://localhost:8080"
    , LOGIN_API_URL : "/user"
    , AUTH_API_URL : "/authenticate"
    , REGISTER_API_URL : "/register"
    , DASHBOARD_URL : "/dashboard"
    , CONTACT_URL : "/contact"
    , CONTACT_SEND_URL : "/sendContactForm"
    , ADD_COURSE_FORM_URL : "/createCourse"
    , MY_COURSES_URL : "/myCourses"
    , ALL_COURSES_URL : "/allCourses"
    , SHOP_URL : "/shop"
    , ADD_SHOP_ITEM_URL : "/addShopItem"
    , SHOP_ITEM_URL : "/shopItem"
    , CART_URL : "/cart"
    , DISCOUNT_CODES_URL : "/discountCodes"
    , GENERATE_DISCOUNT_CODE_URL : "/generateDiscountCode"
    , HOME_URL : "/"
}